# Generated by Django 6.0.2 on 2026-03-06 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='canales/')),
                ('url_sitio', models.URLField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Canales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CanalBolaloca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(blank=True, max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bolaloca - Canal',
                'verbose_name_plural': 'Bolaloca - Canales',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='ConfigStreaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('dominio', models.CharField(help_text='Ej: streamx10.cloud, bolaloca.my', max_length=200)),
                ('ruta', models.CharField(blank=True, help_text='Ej: global1.php?channel=, player/1/', max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuracion Streaming',
                'verbose_name_plural': 'Configuracion Streaming',
            },
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ligas/')),
                ('pais', models.CharField(blank=True, max_length=50)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Ligas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EventoBolaloca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('liga', models.CharField(max_length=100)),
                ('partido', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('canales', models.ManyToManyField(blank=True, to='canales.canalbolaloca')),
            ],
            options={
                'verbose_name': 'Bolaloca - Evento',
                'verbose_name_plural': 'Bolaloca - Eventos',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='BannerImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripcion corta del banner')),
                ('imagen', models.FileField(upload_to='banners/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('canal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='canales.canal')),
                ('liga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='canales.liga')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('youtube', 'YouTube'), ('url_directa', 'URL Directa (MP4/M3U8)'), ('iframe', 'iFrame Personalizado')], default='youtube', max_length=20)),
                ('url_video', models.URLField()),
                ('youtube_id', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('thumbnail_custom', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('stream_id', models.CharField(blank=True, max_length=50)),
                ('tvtvhd_id', models.CharField(blank=True, max_length=50)),
                ('bolaloca_canal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='canales.canalbolaloca')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='canales.canal')),
                ('ligas', models.ManyToManyField(blank=True, related_name='videos', to='canales.liga')),
            ],
            options={
                'verbose_name_plural': 'Videos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='EnlaceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('youtube', 'YouTube'), ('url_directa', 'URL Directa (MP4/M3U8)'), ('iframe', 'iFrame Personalizado')], default='iframe', max_length=20)),
                ('url', models.URLField()),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='canales.video')),
            ],
            options={
                'verbose_name': 'Enlace',
                'verbose_name_plural': 'Enlaces',
                'ordering': ['orden'],
            },
        ),
    ]
