# Generated by Django 6.0.2 on 2026-02-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0002_video_thumbnail_custom_video_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='canales/'),
        ),
        migrations.AlterField(
            model_name='liga',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='ligas/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_custom',
            field=models.FileField(blank=True, help_text='Thumbnail personalizado (para videos no YouTube)', null=True, upload_to='thumbnails/'),
        ),
    ]
