# Generated by Django 6.0.2 on 2026-02-21 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0003_alter_canal_logo_alter_liga_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Opcion 1, ESPN HD, Fox Sports', max_length=100)),
                ('tipo', models.CharField(choices=[('youtube', 'YouTube'), ('url_directa', 'URL Directa (MP4/M3U8)'), ('iframe', 'iFrame Personalizado')], default='iframe', max_length=20)),
                ('url', models.URLField()),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='canales.video')),
            ],
            options={
                'verbose_name': 'Enlace',
                'verbose_name_plural': 'Enlaces',
                'ordering': ['orden'],
            },
        ),
    ]
