# Generated by Django 6.0.2 on 2026-02-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0004_enlacevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='liga',
        ),
        migrations.AddField(
            model_name='video',
            name='ligas',
            field=models.ManyToManyField(blank=True, related_name='videos', to='canales.liga'),
        ),
    ]
