# Generated by Django 6.0.2 on 2026-03-01 01:01

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0013_video_tvtvhd_id_alter_video_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='canal',
            name='url_sitio',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='canalbolaloca',
            name='numero',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='canalbolaloca',
            name='pais',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='enlacevideo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='liga',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='bolaloca_canal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='canales.canalbolaloca'),
        ),
        migrations.AlterField(
            model_name='video',
            name='stream_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_custom',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tvtvhd_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='url_video',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
